# Generated by Django 2.1 on 2022-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
