# Generated by Django 2.1 on 2022-01-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVV_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_num',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month_year',
            field=models.CharField(max_length=5),
        ),
    ]
